config/routes.rb
Rails.application.routes.draw do
  #get '/show' => 'recipes#show
  resource :recipes, only: [:show, :index] do
    get :autocomplete_tag_name, :on => :collection
  end
  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include PgSearch::Model

  has_many :ingredients
  belongs_to :author
  has_and_belongs_to_many :tags

  pg_search_scope :search_by_ingredient, associated_against: {
    ingredients: :name
  }

  pg_search_scope :search_by_tag, associated_against: {
    tags: :name
  }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  autocomplete :tag, :name

  def index
    @people_quantity = Recipe.pluck(:people_quantity).uniq.compact.sort
  end

  def show
    search_input = params["ingredient"].join(" ").downcase

    @recipes = Recipe.search_by_ingredient(search_input)

    if params['people'].present?
      @recipes = @recipes.where(people_quantity: params['people'])
    end

    if params['tag'].reject(&:empty?).present?
      tags = params['tag'].join(" ")
      @recipes = @recipes.search_by_tag(tags)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatDoWeEat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qu'est ce qu'on mange ?</h1>

<%= form_tag recipes_path, method: :get do %>
<div id="ingredients">
  <%= label_tag 'Ingredients' %>
  <%= text_field_tag("ingredient[]", nil, required: true)  %>
  <%= text_field_tag("ingredient[]") %>
  <%= text_field_tag("ingredient[]") %>
</div>

  <%= link_to 'Ajouter un ingrédient', '#', id: 'add_ingredient', onclick: 'addIngredients()', remote: true %>

<div id="people">
  <%= label_tag 'Nombre de personnes' %>
  <%= select_tag "people", options_for_select(@people_quantity), include_blank: true %>
</div>

<div id="tags">
  <%= label_tag 'Affiner ma recherche' %>
  <%=  autocomplete_field_tag 'tag[]', '', autocomplete_tag_name_recipes_path %>
</div>
  <%= link_to 'Ajouter un tag', '#', id: 'add_tag', onclick: 'addTags()', remote: true %>

  <%= submit_tag 'Chercher' %>
<% end %>

<br>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="recipes">
  <% if @recipes.empty? %>
    <span class="no_recipes">Désolé nous n'avons pas trouvé de recettes :(</span>
  <% end  %>
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <h4><%= recipe.name %></h4>
      Temps de préparation/cuisson/total : <br><%= recipe.prep_time %>min / <%= recipe.cook_time %>min / <%= recipe.total_time %>min <br>
      <%= recipe.budget.capitalize %> / <%= recipe.difficulty.capitalize %> <br>
      Pour <%= recipe.people_quantity %> personnes <br>
      Ingredients :
      <ul>
        <% recipe.ingredients.each do |ingredient| %>
          <li><%= ingredient.name %></li>
        <% end %>
      </ul>
      <br>
      Recette par <%= recipe.author.name %><br>
      Note : <%= recipe.rate %>/5
      <br><br>
      Tags: <%= recipe.tags.pluck(:name).join(', ') %>
    </div>
  <% end %>
</div>


<br>
<%= link_to 'Revenir à la recherche', root_path %>